### ISSUE TITLE
Traduction version anglaise

### ISSUE THREAD

**Issue by PaulSherp** [MieuxVoter/mv-front-react#51]
Voici le fichier de traduction vers l'anglais mis à jour. J'ai modifié les deux colonnes et indiqué chaque ligne modifiée avec un commentaire : https://send.firefox.com/download/297565f0e8f34246/#WpX9NQ7DrPVc2bzTgBpzgA

Quelques remarques supplémentaires, suite à l'utilisation de l'application :

1- Après avoir participé à un vote, la page qui confirme la prise en compte du vote contient un bouton "votre avis nous intéresse" (avec un lien vers une google form) : le texte du lien et la google form sont en français ;

2- Lors de la création d'un vote, si on clique sur l’icône "poubelle" pour supprimer le nom d'un candidat, les boutons de confirmation (oui/non) sont en français ;

3- Si on vote avec un mauvais token (lien envoyé par mail et modifié à la main), on peut toujours voir le vote, voter et, après avoir cliqué sur "confirmer", une page vide s'affiche au lieu de la confirmation du vote ; est-il possible soit de détecter un mauvais token plus tôt, soit d'avoir un message d'erreur approprié ?

4- Si on clique sur un mauvais lien de vote, on voit un message d'erreur (élection inconnue) mais pas de bouton pour revenir à la page d'accueil ;

5- Si on clique sur un mauvais lien de résultats, on voit un message d'erreur et un bouton rouge pour revenir à la page d'accueil mais le texte du bouton n'est pas dans le fichier de traduction (il n'y a pas d'entrée "Back to home page", ce qui empêche de le corriger pour "Back to homepage"). Il y a une entrée similaire mais ce n'est pas la même que sur le bouton ;

6- Enfin, le texte de l'email envoyé pour le vote peut être corrigé aussi.

Voilà, j'espère que cela aide !

**Comment by guhur** [comment]
Fixed.
